name: ML CI Pipeline

on:
  push:
    branches: [ main ]

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          python -m nltk.downloader stopwords


  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install -r requirements.txt
      - run: pytest || echo "No tests"


  dvc_check:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Verify DVC Files
        run: |
          ls data
          ls dvc.yaml
          echo "DVC pipeline structure verified"


  train:
    runs-on: ubuntu-latest
    needs: dvc_check
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Reset MLflow DB
        run: rm -f mlflow.db

      - name: Train Model (MLflow Tracking)
        run: python src/train.py

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: models/sentiment_model.pkl


  validate:
    runs-on: ubuntu-latest
    needs: train
    steps:
      - uses: actions/checkout@v3

      - name: Download Model Artifact
        uses: actions/download-artifact@v4
        with:
          name: model
          path: models/

      - name: Validate Model Output
        run: |
          if [ -f models/sentiment_model.pkl ]; then
            echo "Model exists"
          else
            echo "Model missing" && exit 1
          fi


  api_check:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v3

      - name: Check API File
        run: |
          if [ -f src/api.py ]; then
            echo "API present"
          else
            echo "API missing" && exit 1
          fi


  docker_check:
    runs-on: ubuntu-latest
    needs: api_check
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t sentiment-api .


  monitoring_check:
    runs-on: ubuntu-latest
    needs: docker_check
    steps:
      - uses: actions/checkout@v3

      - name: Check Monitoring Script
        run: |
          if [ -f src/monitor.py ]; then
            echo "Monitoring ready"
          else
            echo "Monitoring missing" && exit 1
          fi